{{- with $.Values }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ include "synology-csi.fullname" $ }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "synology-csi.fullname" $ }}-controller
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "synology-csi.fullname" $ }}-controller
{{- end }}
