{{- with $.Values }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ include "synology-csi.fullname" $ }}-controller
{{- end }}
