{{- if $.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1/VolumeSnapshotClass" }}
{{- range $name, $_ := $.Values.volumeSnapshotClasses }}
{{- if not .disabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
{{- with .deletionPolicy }}
deletionPolicy: {{ . }}
{{- end }}
driver: csi.san.synology.com
kind: VolumeSnapshotClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ default "false" .isDefault | quote }}
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ printf "%s-%s" (include "synology-csi.fullname" $) $name }}
{{- with .parameters }}
parameters: {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
